# Generated by Django 3.2.9 on 2021-12-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='post',
        ),
    ]
