# Generated by Django 3.2.9 on 2021-12-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_situation_post'),
        ('Immo', '0005_auto_20211212_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.situation'),
        ),
    ]
